"""Added the concept of a user

Revision ID: 7093dd9953e6
Revises: 
Create Date: 2019-05-28 17:15:46.164760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7093dd9953e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('lastname', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('postal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
